### ISSUE TITLE
react-native run-ios BUILD-FAILED

### ISSUE THREAD

**Issue by maithuy** [shoutem/platform#42]
Steps:

Create an app on the Shoutem builder site
Login via terminal and Clone the app
Run react-native run-ios

Scanning folders for symlinks in /Users/thuynguyen/Development/alohahealthnetwork/aloha-app/node_modules (24ms)
Found Xcode workspace AlohaApp.xcworkspace
Building using "xcodebuild -workspace AlohaApp.xcworkspace -configuration Debug -scheme AlohaApp -destination id=80A240B5-8F78-4DCA-BBF3-8465E2409816 -derivedDataPath build"
User defaults from command line:

    IDEDerivedDataPathOverride = /Users/thuynguyen/Development/alohahealthnetwork/aloha-app/ios/build

note: Using new build system

note: Planning build

note: Constructing build description

Build system information

error: /Users/thuynguyen/Development/alohahealthnetwork/aloha-app/ios/Pods/Target Support Files/Pods-AlohaApp/Pods-AlohaApp.debug.xcconfig: unable to open file (in target "AlohaApp" in project "AlohaApp") (in target 'AlohaApp')

Build system information

error: /Users/thuynguyen/Development/alohahealthnetwork/aloha-app/ios/Pods/Target Support Files/Pods-AlohaApp/Pods-AlohaApp.debug.xcconfig: unable to open file (in target "AlohaApp" in project "AlohaApp") (in target 'AlohaApp')

Build system information

error: /Users/thuynguyen/Development/alohahealthnetwork/aloha-app/ios/Pods/Target Support Files/Pods-AlohaApp/Pods-AlohaApp.debug.xcconfig: unable to open file (in target "AlohaApp" in project "AlohaApp") (in target 'AlohaApp')

Build system information

error: /Users/thuynguyen/Development/alohahealthnetwork/aloha-app/ios/Pods/Target Support Files/Pods-AlohaApp/Pods-AlohaApp.debug.xcconfig: unable to open file (in target "AlohaApp" in project "AlohaApp") (in target 'AlohaApp')

Build system information

warning: The iOS Simulator deployment target is set to 7.0, but the range of supported deployment target versions for this platform is 8.0 to 12.1. (in target 'RNVectorIcons')

Build system information

warning: The iOS Simulator deployment target is set to 7.0, but the range of supported deployment target versions for this platform is 8.0 to 12.1. (in target 'RCTRestart')

Build system information

warning: The iOS Simulator deployment target is set to 7.0, but the range of supported deployment target versions for this platform is 8.0 to 12.1. (in target 'SplashScreen')

Build system information

warning: The iOS Simulator deployment target is set to 7.0, but the range of supported deployment target versions for this platform is 8.0 to 12.1. (in target 'RCTVideo')

Build system information

warning: The iOS Simulator deployment target is set to 7.0, but the range of supported deployment target versions for this platform is 8.0 to 12.1. (in target 'RNFlurryAnalytics')

Build system information

warning: The iOS Simulator deployment target is set to 7.0, but the range of supported deployment target versions for this platform is 8.0 to 12.1. (in target 'RNShopify')

Build system information

warning: The iOS Simulator deployment target is set to 7.0, but the range of supported deployment target versions for this platform is 8.0 to 12.1. (in target 'RCTGoogleAnalyticsBridge')

Build system information

warning: Capabilities for AlohaApp may not function correctly because its entitlements use a placeholder team ID. To resolve this, select a development team in the build settings editor. (in target 'AlohaApp')

** BUILD FAILED **

Installing build/Build/Products/Debug-iphonesimulator/AlohaApp.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=22):
Failed to install the requested application
The bundle identifier of the application could not be determined.
Ensure that the application's Info.plist contains a value for CFBundleIdentifier.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/AlohaApp.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

**Comment by maithuy** [comment]
I tried opting out from New Build System
Open AppName/ios/AppName.xcworkspace , in Xcode, click on File -> Workspace settings... and then set the build system to the legacy one.

It still failed.

**Comment by Vladimir-Vdovic** [comment]
It looks like your deployment target is too low for our dependencies:

```
the iOS Simulator deployment target is set to 7.0, but the range of supported deployment target versions for this platform is 8.0 to 12.1. 
```

Upping the simulator deployment target to 8.0 should resolve the issue, let us know.

**Comment by maithuy** [comment]
The xcode deployment target setting was 10 which was already higher 8.0. 
Setting to 8 still doesn't resolve the issue

Scanning folders for symlinks in /Users/thuynguyen/Development/alohahealthnetwork/aloha-app/node_modules (24ms)
Found Xcode workspace AlohaApp.xcworkspace
Building using "xcodebuild -workspace AlohaApp.xcworkspace -configuration Debug -scheme AlohaApp -destination id=80A240B5-8F78-4DCA-BBF3-8465E2409816 -derivedDataPath build"
User defaults from command line:

    IDEDerivedDataPathOverride = /Users/thuynguyen/Development/alohahealthnetwork/aloha-app/ios/build


note: Using new build system

note: Planning build

note: Constructing build description

Build system information

**error: /Users/thuynguyen/Development/alohahealthnetwork/aloha-app/ios/Pods/Target Support Files/Pods-AlohaApp/Pods-AlohaApp.debug.xcconfig: unable to open file (in target "AlohaApp" in project "AlohaApp") (in target 'AlohaApp')**



Build system information

error: /Users/thuynguyen/Development/alohahealthnetwork/aloha-app/ios/Pods/Target Support Files/Pods-AlohaApp/Pods-AlohaApp.debug.xcconfig: unable to open file (in target "AlohaApp" in project "AlohaApp") (in target 'AlohaApp')



Build system information

error: /Users/thuynguyen/Development/alohahealthnetwork/aloha-app/ios/Pods/Target Support Files/Pods-AlohaApp/Pods-AlohaApp.debug.xcconfig: unable to open file (in target "AlohaApp" in project "AlohaApp") (in target 'AlohaApp')



Build system information

error: /Users/thuynguyen/Development/alohahealthnetwork/aloha-app/ios/Pods/Target Support Files/Pods-AlohaApp/Pods-AlohaApp.debug.xcconfig: unable to open file (in target "AlohaApp" in project "AlohaApp") (in target 'AlohaApp')



Build system information

warning: The iOS Simulator deployment target is set to 7.0, but the range of supported deployment target versions for this platform is 8.0 to 12.1. (in target 'RNVectorIcons')



Build system information

warning: The iOS Simulator deployment target is set to 7.0, but the range of supported deployment target versions for this platform is 8.0 to 12.1. (in target 'RCTRestart')



Build system information

warning: The iOS Simulator deployment target is set to 7.0, but the range of supported deployment target versions for this platform is 8.0 to 12.1. (in target 'SplashScreen')



Build system information

warning: The iOS Simulator deployment target is set to 7.0, but the range of supported deployment target versions for this platform is 8.0 to 12.1. (in target 'RCTVideo')


Build system information


warning: The iOS Simulator deployment target is set to 7.0, but the range of supported deployment target versions for this platform is 8.0 to 12.1. (in target 'RNFlurryAnalytics')



Build system information

warning: The iOS Simulator deployment target is set to 7.0, but the range of supported deployment target versions for this platform is 8.0 to 12.1. (in target 'RCTGoogleAnalyticsBridge')



Build system information

warning: The iOS Simulator deployment target is set to 7.0, but the range of supported deployment target versions for this platform is 8.0 to 12.1. (in target 'RNShopify')



Build system information

warning: Capabilities for AlohaApp may not function correctly because its entitlements use a placeholder team ID. To resolve this, select a development team in the build settings editor. (in target 'AlohaApp')



** BUILD FAILED **


Installing build/Build/Products/Debug-iphonesimulator/AlohaApp.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=22):
Failed to install the requested application
The bundle identifier of the application could not be determined.
Ensure that the application's Info.plist contains a value for CFBundleIdentifier.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/AlohaApp.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

**Comment by Vladimir-Vdovic** [comment]
I just noticed that you noted you're using the new build system.

Unfortunately, React Native currently doesn't support the new build system which is the default as of Xcode 10.

The new build system will be supported as of React Native 0.58.0. Our platform currently uses 0.56.0.

You can specify the Legacy build system by opening the AppName.xcworkspace with Xcode, then selecting the "File" dropdown menu from the top bar and opening "Workspace settings...".

There you can specify the build system being used. Selecting the legacy one should resolve the issue.

**Comment by maithuy** [comment]
I set "Build System" to "Legacy Build System" for both "Shared Workspace Settings" and "Per-User Workspace Settings" and running 'react-native run-ios' has 'build succeeded' status, the Simulator does kick off. However, the app is stuck at the "Launch screen", please see attached screenshot.

It'd be great if you could pin point  how to fix this

![launch-screen-stuck](https://user-images.githubusercontent.com/2032654/52602317-0a184900-2e17-11e9-9ad1-0a276dcec89a.jpg)

**Comment by maithuy** [comment]
Thanks, setting Legacy Build system resolves this.

**Comment by narenderv7** [comment]
@maithuy How did you set a legacy build system?

**Comment by alexanderturner** [comment]
File -> Project Settings @narenderv7

**Comment by lfoliveir4** [comment]
For versions above React 0.65, go to File> Workspace Settings and change the build to Legacy.

Go to the React Native IOS folder, reinstall the pods using the "pod install" command.

Clean up the project with the command: Shift + Command + K and build the project again.

**Comment by qodehub-nanadjei** [comment]
This solution should help you out.

https://github.com/facebook/react-native/issues/24450#issuecomment-516760157

**Comment by khadafirp** [comment]
> For versions above React 0.65, go to File> Workspace Settings and change the build to Legacy.
> 
> Go to the React Native IOS folder, reinstall the pods using the "pod install" command.
> 
> Clean up the project with the command: Shift + Command + K and build the project again.



> For versions above React 0.65, go to File> Workspace Settings and change the build to Legacy.
> 
> Go to the React Native IOS folder, reinstall the pods using the "pod install" command.
> 
> Clean up the project with the command: Shift + Command + K and build the project again.

excuse me sir, I need a help, I'm not find to change the build to legacy in workspace setting

**Comment by khadafirp** [comment]
excuse me sir @lfoliveir4, excuse me sir, I'm not find to change the build to legacy in workspace setting. please help. thank you

**Comment by khadafirp** [comment]
excuse me sir @lfoliveir4, I'm not find to change the build to legacy in workspace setting. please help. thank you
